name: shopify
description: Shopify's flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0

  json_annotation: ^0.2.3
  shared_preferences: ^0.5.3
  flutter_webview_plugin: ^0.3.0+2
  flutter_pagewise: 1.0.0
  intl: ^0.15.6
  loadmore: ^1.0.1
  jvanila_flutter:
    git: git://github.com/pavan2you/flutter-mvp-framework
#    path: ../flutter-mvp-framework

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.jvanila.flutter.shopify
    pluginClass: ShopifyPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
